baseURL = 'https://hlxuan.github.io/'
locale = 'zh-CN'
title = "Hlxuan's Blog"
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

mainsections = ["posts", "papermod"]

[minify]
  disableXML = true
  # minifyOutput = true

[pagination]
  disableAliases = false
  pagerSize = 3

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = "en"
label = "English"
weight = 1
title = "Hlxuan's Blog"

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = -1

[[languages.en.menu.main]]
name = "Works"
url = "https://www.hlxuan.top/works"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 2

[[languages.en.menu.main]]
name = "Search"
url = "search"
weight = 2

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 3

[outputFormats.llms]
  mediaType = "text/plain"
  baseName = "llms"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON", "llms"]

[params]
env = "production"
title = "Hlxuan's Blog"
author = "Hlxuan"
favicon = "/favicon.ico"

defaultTheme = "auto"

ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
comments = false

[languages.en.params.homeInfoParams]
  Title = "Hi! Nice to have you here. 👋"
  Content = """
  Welcome to my blog.
  - I am a software engineer and short video creator.
  - I’m interested in Front-end development, Miniprogram development.
  - I’m currently learning Full-stack development, other programming languages.
  - I will share some content from time to time.
  """
  
[[params.socialIcons]]
name = "github"
title = "My Github."
url = "https://github.com/Hlxuan."

[[params.socialIcons]]
  name = "other"
  title = "My Website"
  url = "https://www.hlxuan.top"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true